### ISSUE TITLE
Change the argument of the slice function to double.

### ISSUE THREAD

**Issue by hayato-m126** [tier4/ros2bag_extensions#4]
@KeisukeShima 

In the current implementation, the arguments of the slice function are int type start_time and duration.
However, what is displayed in the ros2 bag info is a double type in milliseconds, and if you want to use an int, you have to take out the decimal point and complement it with 000000 afterwards.
Why don't you make it a double type to make it easier for users to input?
Also, I thought it would be easier to use if there was a way to specify only the start time or only the end time.

**Comment by KeisukeShima** [comment]
Great suggestion! The current implementation is very basic, so I welcome this suggestion.
